from theiaide/theia-java:1.0.0
user root

run wget https://github.com/spgennard/vscode_cobol/releases/download/6.0.23/cobol-6.0.23.vsix && \
  mv *.vsix /home/theia/plugins && \
  mkdir /home/node/.zowe && \
  chown -R 1000:1000 /home/. ;
user 1000
